#!/usr/bin/env node
/* Splits the brand lockup SVG (vendor/sm-motion/assets/smedia-full.svg) into
   the four paths the Rocket Sting animates — body, small blast (always lit),
   large blast (the boost fill + its green stroke outline) and the wordmark —
   and writes them to src/brand/lockup.js as data. Same split as
   scripts/logo-lockup.mjs in the motiondesign repo, so every surface shares
   one lockup. Run: npm run lockup */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(new URL('..', import.meta.url).pathname);
const svg = readFileSync(resolve(ROOT, 'vendor/sm-motion/assets/smedia-full.svg'), 'utf8');
const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*>/g)].map((m) => m[1]);
if (paths.length < 4) throw new Error('unexpected logo svg structure: expected 4 paths, got ' + paths.length);
const [body, boost, blast, wordmark] = paths;

const out = `/* GENERATED by scripts/build-lockup.mjs from vendor/sm-motion/assets/smedia-full.svg.
   Do not edit — re-run \`npm run lockup\` after re-vendoring the logo.
   viewBox is the full lockup; the mark alone fits in the first 70 units. */
export const LOCKUP_VIEWBOX = '0 0 736.71 162.15';
export const MARK_VIEWBOX = '0 0 70 162.15';
export const LOCKUP_RATIO = 736.71 / 162.15; // width / height
/* Logo asset colors — the two blasts are part of the supplied mark, not UI tokens. */
export const BLAST_SMALL = '#aacb33'; // palette-lint-ignore: logo asset color
export const BLAST_LARGE = '#c9e465'; // palette-lint-ignore: logo asset color
export const LOCKUP = {
  body: ${JSON.stringify(body)},
  blast: ${JSON.stringify(blast)},
  boost: ${JSON.stringify(boost)},
  wordmark: ${JSON.stringify(wordmark)},
};
`;
writeFileSync(resolve(ROOT, 'src/brand/lockup.js'), out);
console.log('wrote src/brand/lockup.js (' + out.length + ' bytes)');
